export const SET_CUSTOMER = 'SET_CUSTOMER';
export const GET_CUSTOMER = 'GET_CUSTOMER';
export const CUSTOMER_REQUEST = 'CUSTOMER_REQUEST';
export const EDIT_PROFILE_REQUEST = 'EDIT_PROFILE_REQUEST';
export const EDIT_PROFILE_PASS_REQUEST = 'EDIT_PROFILE_PASS_REQUEST';
export const CHECK_AUTH = 'CHECK_AUTH';

export const SET_POPUP_VALIDATOR = 'SET_POPUP_VALIDATOR';
export const CLEAR_POPUP_VALIDATOR = 'CLEAR_POPUP_VALIDATOR';

export const GET_SLIDES = 'GET_SLIDES';

export const GET_PRODUCTS_MENU = "GET_PRODUCTS_MENU"
export const WAIT_PRODUCTS_MENU = "WAIT_PRODUCTS_MENU";

export const GET_PRODUCTS_FILTERS = "GET_PRODUCTS_FILTERS"
export const WAIT_PRODUCTS_FILTERS = "WAIT_PRODUCTS_FILTERS";

export const GET_RECOMMENDED_PRODUCTS = "GET_RECOMMENDED_PRODUCTS";

export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const GET_PRODUCTS_REQUEST = 'GET_PRODUCTS_REQUEST';

export const ADD_SUBSCRIBER = "ADD_SUBSCRIBER";
export const CLOSE_MODAL = "CLOSE_MODAL";